# Generated by Django 3.1.14 on 2023-04-14 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('last', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('pic', models.ImageField(default='', max_length=1000, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('education', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('phone', models.IntegerField(blank=True, default=0, null=True)),
                ('about', models.CharField(blank=True, default='None', max_length=1000, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
