# Generated by Django 3.1.14 on 2023-04-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authMain', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='https://res.cloudinary.com/dizjm7yrb/image/upload/v1679930612/profile_img/u2hphaff7nxk1uyf09us.png', max_length=1000, upload_to=''),
        ),
    ]
